name: Build and Deploy to Digital Ocean

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-images:
    name: Build and push images to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract repository owner lowercase
        id: repo-owner
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ steps.repo-owner.outputs.owner }}/interbet-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.repo-owner.outputs.owner }}/interbet-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            API_URL=/api

  redeploy:
    name: Deploy to staging environment
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Deploy to staging server
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.DEPLOY_WEBHOOK_URL }}/redeploy-application
          webhook_auth_type: "header"
          webhook_auth: "X-Auth-Secret:${{ secrets.WEBHOOK_AUTH_SECRET }}"
          data: '{"repository":"${{ github.repository }}", "commit":"${{ github.sha }}"}'
